//
//  SecureKeys-Profile.xcconfig
//  Walmart
//
//  Created by Alexandre Oliveira Santos on 5/10/21.
//  Copyright © 2021 Walmart. All rights reserved.
//

// Configuration settings file format documentation can be found at:
// https://help.apple.com/xcode/#/dev745c5c974

#include "SecureKeys-Base.xcconfig"

COMPASS_PROD_LOGGED_IN_CONSUMER_ID=""
COMPASS_STAGE_LOGGED_IN_CONSUMER_ID=""
COMPASS_PROD_GUEST_CONSUMER_ID=""
COMPASS_STAGE_GUEST_CONSUMER_ID=""
COMPASS_PROD_GUEST_CLIENT_SECRET=""
COMPASS_STAGE_GUEST_CLIENT_SECRET=""

GCC_PREPROCESSOR_DEFINITIONS = $(inherited) BRAZE_KEY=${BRAZE_API_KEY} PERIMETERX_KEY=${PERIMETERX_API_KEY} PERIMETERX_KEY_DEBUG=${PERIMETERX_API_DEBUG_KEY} APPSFLYER_DEV_KEY=${APPSFLYER_API_DEV_KEY} APPSFLYER_APP_ID=${APPSFLYER_API_APP_ID} APPSFLYER_APP_ID=${APPSFLYER_API_APP_ID} APPSFLYER_ONELINK_AUTH=${APPSFLYER_ONELINK_API_AUTH} APPSFLYER_ONELINK_AUTH=${APPSFLYER_ONELINK_API_AUTH} THREATMETRIX_PROD_ORG_ID=${THREATMETRIX_API_PROD_ORG_ID} ENCRYPTION_KEY=${ENCRYPTION_PRIVATE_KEY} FLIPP_KEY=${FLIPP_API_KEY} FIS_PAYPAGEID_KEY=${FIS_PAYPAGEID_API_KEY} FIS_PAYPAGEID_PROD_KEY=${FIS_PAYPAGEID_PROD_API_KEY}  ID_ME_CLIENT_ID_KEY=${ID_ME_CLIENT_ID}  QUANTUMMETRIC_UID=${QUANTUMMETRIC_API_UID} QUANTUMMETRIC_STAGE_UID=${QUANTUMMETRIC_STAGE_API_UID} TSL_SECRETE_DEV=${TSL_DEV_SHARED_SECRETE} TSL_SECRETE=${TSL_SHARED_SECRETE} TSL_KEY_DEV=${TSL_DEV_CLIENT_KEY} TSL_KEY=${TSL_CLIENT_KEY} LIVESTREAM_SALT_DEV=${LIVESTREAM_DEV_SALT_KEY} LIVESTREAM_SALT=${LIVESTREAM_SALT_KEY} DSG_NATIVE_PARTNER_KEY=${DSG_NATIVE_PARTNER_API_KEY} DSG_NATIVE_PARTNER_SERVICE_KEY=${DSG_NATIVE_PARTNER_API_SERVICE_KEY} AROPTICAL_PROD=${AROPTICAL_PROD_KEY} AROPTICAL_DEV=${AROPTICAL_DEV_KEY} COMPASS_PROD_LOGGED_IN_CONSUMER_ID=${COMPASS_PROD_LOGGED_IN_CONSUMER_ID} COMPASS_STAGE_LOGGED_IN_CONSUMER_ID=${COMPASS_STAGE_LOGGED_IN_CONSUMER_ID} COMPASS_PROD_GUEST_CONSUMER_ID=${COMPASS_PROD_GUEST_CONSUMER_ID} COMPASS_STAGE_GUEST_CONSUMER_ID=${COMPASS_STAGE_GUEST_CONSUMER_ID} COMPASS_PROD_GUEST_CLIENT_SECRET=${COMPASS_PROD_GUEST_CLIENT_SECRET} COMPASS_STAGE_GUEST_CLIENT_SECRET=${COMPASS_STAGE_GUEST_CLIENT_SECRET}
