//
//  SecureKeys-Release.xcconfig
//  Walmart
//
//  Created by Alexandre Oliveira Santos on 5/10/21.
//  Copyright © 2021 Walmart. All rights reserved.
//

// Configuration settings file format documentation can be found at:
// https://help.apple.com/xcode/#/dev745c5c974

// SDK Keys (important not to name them exactly the same as preprocessor definition)
BRAZE_API_KEY="BRAZE_PROD"
PERIMETERX_API_KEY="PERIMETERX_PROD"
PERIMETERX_API_DEBUG_KEY="PX2GWLiA5B"
// AppsFlyer's Dev Key, used both in debug and release modes
APPSFLYER_API_DEV_KEY="APPSFLYER_DEV_KEY_PROD"
APPSFLYER_API_APP_ID="APPSFLYER_APP_ID_PROD"
APPSFLYER_ONELINK_API_AUTH="APPSFLYER_ONELINK_AUTH_PROD"
// ThreatMetrix orgID is provided by CCM. This is a fallback.
THREATMETRIX_API_PROD_ORG_ID="THREATMETRIX_PROD_ORG_ID_PROD"
// Encryption key used by different features to encrypt/decrypt strings.
ENCRYPTION_PRIVATE_KEY="ENCRYPTION_PRIVATE_KEY_PROD"

// FIS Pay Key
FIS_PAYPAGEID_KEY="FIS_PAYPAGEID_TEFLON"
FIS_PAYPAGEID_PROD_API_KEY="FIS_PAYPAGEID_PROD_DUMMY"

// Fit Predictor
FIT_PREDICTOR_PARTNER_API_KEY="FIT_PREDICTOR_PARTNER_KEY_PROD"
FIT_PREDICTOR_SERVICE_API_KEY="FIT_PREDICTOR_SERVICE_KEY_PROD"
FIT_PREDICTOR_EMAIL_SALT_VALUE="FIT_PREDICTOR_EMAIL_SALT_PROD"

FLIPP_API_KEY="FLIPP_PROD"

QUANTUMMETRIC_API_UID="QUANTUMMETRIC_PROD"
QUANTUMMETRIC_STAGE_API_UID="503f16b5-5445-4b35-9d77-3ca9a9154f27"

BAZAARVOICE_LICENCE_KEY="BAZAARVOICE_PROD"
COMPASS_PROD_LOGGED_IN_CONSUMER_ID="COMPASS_PROD_LOGGED_IN_CONSUMER_ID_PROD"
COMPASS_STAGE_LOGGED_IN_CONSUMER_ID="COMPASS_STAGE_LOGGED_IN_CONSUMER_ID_STAGE"
COMPASS_PROD_GUEST_CONSUMER_ID="COMPASS_PROD_GUEST_CONSUMER_ID_PROD"
COMPASS_STAGE_GUEST_CONSUMER_ID="COMPASS_STAGE_GUEST_CONSUMER_ID_STAGE"
COMPASS_PROD_GUEST_CLIENT_SECRET="COMPASS_PROD_GUEST_CLIENT_SECRET_PROD"
COMPASS_STAGE_GUEST_CLIENT_SECRET="COMPASS_STAGE_GUEST_CLIENT_SECRET_STAGE"

//Livestream keys that looper will replace
TSL_SHARED_SECRETE="TSL_SHARED_SECRETE_PROD"
TSL_DEV_SHARED_SECRETE="TSL_DEV_SHARED_SECRETE_PROD"
TSL_CLIENT_KEY="TSL_CLIENT_KEY_PROD"
TSL_DEV_CLIENT_KEY="TSL_DEV_CLIENT_KEY_PROD"
LIVESTREAM_SALT_KEY="LIVESTREAM_SALT_KEY_PROD"
LIVESTREAM_DEV_SALT_KEY="LIVESTREAM_DEV_SALT_KEY_PROD"

DSG_NATIVE_PARTNER_API_KEY="DSG_NATIVE_PARTNER_KEY_PROD"
DSG_NATIVE_PARTNER_API_SERVICE_KEY="DSG_NATIVE_PARTNER_SERVICE_KEY_PROD"
AROPTICAL_KEY="AROPTICAL_KEY_PROD"
AROPTICAL_DEV_KEY="AROPTICAL_KEY_DEV"

GCC_PREPROCESSOR_DEFINITIONS = $(inherited) BRAZE_KEY=${BRAZE_API_KEY} PERIMETERX_KEY=${PERIMETERX_API_KEY} PERIMETERX_KEY_DEBUG=${PERIMETERX_API_DEBUG_KEY} APPSFLYER_DEV_KEY=${APPSFLYER_API_DEV_KEY} APPSFLYER_APP_ID=${APPSFLYER_API_APP_ID} APPSFLYER_ONELINK_AUTH=${APPSFLYER_ONELINK_API_AUTH} THREATMETRIX_PROD_ORG_ID=${THREATMETRIX_API_PROD_ORG_ID} ENCRYPTION_KEY=${ENCRYPTION_PRIVATE_KEY} FIS_PAYPAGEID_PROD_KEY=${FIS_PAYPAGEID_PROD_API_KEY} FLIPP_KEY=${FLIPP_API_KEY} FIT_PREDICTOR_PARTNER_KEY=${FIT_PREDICTOR_PARTNER_API_KEY} FIT_PREDICTOR_SERVICE_KEY=${FIT_PREDICTOR_SERVICE_API_KEY} FIT_PREDICTOR_EMAIL_SALT=${FIT_PREDICTOR_EMAIL_SALT_VALUE} ID_ME_CLIENT_ID_KEY=${ID_ME_CLIENT_ID} QUANTUMMETRIC_UID=${QUANTUMMETRIC_API_UID} QUANTUMMETRIC_STAGE_UID=${QUANTUMMETRIC_STAGE_API_UID} BAZAARVOICE_KEY=${BAZAARVOICE_LICENCE_KEY}  TSL_SECRETE_DEV=${TSL_DEV_SHARED_SECRETE} TSL_SECRETE=${TSL_SHARED_SECRETE} TSL_KEY_DEV=${TSL_DEV_CLIENT_KEY} TSL_KEY=${TSL_CLIENT_KEY} LIVESTREAM_SALT_DEV=${LIVESTREAM_DEV_SALT_KEY} LIVESTREAM_SALT=${LIVESTREAM_SALT_KEY}  DSG_NATIVE_PARTNER_KEY=${DSG_NATIVE_PARTNER_API_KEY} DSG_NATIVE_PARTNER_SERVICE_KEY=${DSG_NATIVE_PARTNER_API_SERVICE_KEY} AROPTICAL_PROD=${AROPTICAL_KEY} AROPTICAL_DEV=${AROPTICAL_DEV_KEY} COMPASS_PROD_LOGGED_IN_CONSUMER_ID=${COMPASS_PROD_LOGGED_IN_CONSUMER_ID} COMPASS_STAGE_LOGGED_IN_CONSUMER_ID=${COMPASS_STAGE_LOGGED_IN_CONSUMER_ID} COMPASS_PROD_GUEST_CONSUMER_ID=${COMPASS_PROD_GUEST_CONSUMER_ID} COMPASS_STAGE_GUEST_CONSUMER_ID=${COMPASS_STAGE_GUEST_CONSUMER_ID} COMPASS_PROD_GUEST_CLIENT_SECRET=${COMPASS_PROD_GUEST_CLIENT_SECRET} COMPASS_STAGE_GUEST_CLIENT_SECRET=${COMPASS_STAGE_GUEST_CLIENT_SECRET}
