import React, {useState} from 'react'
import { useNavigate } from 'react-router-dom'

import {preview} from '../assets';

import {getRandomPrompt} from '../Utils';
import { Formsfield, Loader} from '../components';

const CreatePost = () => {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    name : '',
    prompt:'',
    photo:'',
  })
  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async(e) =>{
    e.preventDefault();

    if(form.prompt && form.photo){

      setLoading(true);
      try{
        const response = await fetch('http://localhost:3001/api/v1/post',
        {
          method:'POST',
          headers: {
            'Content-type': 'application/json',
          },
          body: JSON.stringify(form)
        })
        await response.json();
        navigate('/');
      }catch(err){
        console.error(err);

        alert(err)
      }
      finally{
        setLoading(false);
      }
    } else {
        alert('please enter a prompt and generate an image')
      }

  }
  const generatingImage = async () =>{
    // first we check if there is a prompt
    if(form.prompt){
      try{

        setGeneratingImg(true);
        const response = await fetch('http://localhost:3001/api/v1/dalle',{
          method : 'POST',
          headers : {
            'content-type': 'application/json',

          },
          body: JSON.stringify({prompt: form.prompt}),
        })
        const data = await response.json();
        // this is the way we ae going to save our data and render our im age
        setForm({...form, photo:`data:image/jpeg;base64, $
        {data.photo}`})
      }catch(error){
        alert(error);

      }
      finally {
        setGeneratingImg(false)
      }
    } else{
      alert('please enter a prompt')
    }

  }
  const handleChange = (e) =>{
    setForm({...form, [e.target.name]: e.target.value})

  }
  const handleSurpriseMe = () => {
    const RandomPrompt = getRandomPrompt(form.prompt);
    setForm({...form, prompt: RandomPrompt})

  }

  return (
    <section className='max-w-7xl mx-auto'>
   
     <div>
        <h1 className=' font-extrabold text-[#222328] text-[32px]'>Create</h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>Create a collection of imaginative visuallly stunning images generated by Dall-E and share them with the community</p>
      
     </div>
    <form className='mt-16 max-w-3xl' onSubmit= {handleSubmit}>
      <div className=' = flex flex-col gap-5'>
        <Formsfield 
        LabelName = "Your Name"
        type = "text"
        name = "name"
        placeHolder = "John Doe"
        value = {form.name}
        handleChange = {handleChange}
        />
        <Formsfield 
        LabelName = "Your Prompt"
        type = "text"
        name = "prompt"
        placeHolder = "A Plush toy robot sitting against a yello wall"
        value = {form.prompt}
        handleChange = {handleChange}
        isSurpriseMe 
        handleSurpriseMe = {handleSurpriseMe}
        />
        <div className='relative bg-gray-50 border border-gray-300 text-gray-300
        text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3
        h-64 flex justify-center items-center'>
          {form.photo ? (
            <img src ={form.photo}
            alt = {form.prompt}
            className="w-full h-full object-contain"/>

          ):(
            <img src = {preview}
            alt = "preview"
            className='w-9/12 h-9/12 object-contain opacity-40'
            />
          )}
           {/* The following is for if there is an image being generated */}
          {generatingImg && (
            <div className='absolute insert-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)]
            rounded-lg'>
              <Loader/>
            </div>
          )}

        </div>


      </div>
      {/*creating a submiyt button */}
    <div className='mt-5 flex gap-5'>
      <button type = "button"
      onClick={generatingImage}
      className='text-white bg-green-700 font-medium rounded-md text-sm w-full sm:w-auto
      px-5 py-2.5 text-center'>
        {generatingImg ? 'Generating..' : "Generate image"}

        </button>
    </div>
    <div className='mt-10'>
      <p className='mt-2 text-[#666e75] text-[14px]'>Once You have created the Image you want
      , you can share it with the community.</p>
      <button
      type = "submit"
      className='mt-3 text-white bg-[#6469ff]
      font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'> 
      {loading ? "Sharing...":"Share with the community"}</button>

    </div>
    </form>




    </section>
  )
}

export default CreatePost